name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - run: kotlinc src/main/kotlin/replics.kt -d /tmp/replics.jar 
      - run: kotlinc src/main/kotlin/Main.kt -include-runtime -d /tmp/hello.jar; -d /tmp/replics.jar; java -jar /tmp/hello.jar
      - run: kotlin Main.main.kts
